package com.petlove.weblove.common.error;

public enum ErrorCode {
    OK,
    INVALID_PARAM,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    INTERNAL_ERROR,
    AUTH_OTP_INVALID,
    AUTH_OTP_EXPIRED,
    AUTH_OTP_TOO_FREQUENT,
    AUTH_TOKEN_INVALID,
    AUTH_REFRESH_TOKEN_INVALID,
    USER_DISABLED,
    USER_BANNED,
    FILE_TYPE_NOT_ALLOWED,
    FILE_TOO_LARGE,
    FILE_NOT_READY,
    STATE_TRANSITION_INVALID,
    VERIFICATION_REAL_NAME_REQUIRED,
    VERIFICATION_ALREADY_APPROVED,
    VERIFICATION_NOT_FOUND,
    VERIFICATION_STATUS_INVALID,
    VERIFICATION_FILE_INVALID,
    VERIFICATION_FILE_NOT_OWNED,
    VERIFICATION_SUBMIT_NOT_ALLOWED,
    VERIFICATION_REVIEW_NOT_ALLOWED
}
